# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20130219215751) do

  create_table "regions", :force => true do |t|
    t.string "name"
  end

  create_table "weeks", :force => true do |t|
    t.string  "date"
    t.integer "United States"
    t.integer "Alabama"
    t.integer "Alaska"
    t.integer "Arizona"
    t.integer "Arkansas"
    t.integer "California"
    t.integer "Colorado"
    t.integer "Connecticut"
    t.integer "Delaware"
    t.integer "District of Columbia"
    t.integer "Florida"
    t.integer "Georgia"
    t.integer "Hawaii"
    t.integer "Idaho"
    t.integer "Illinois"
    t.integer "Indiana"
    t.integer "Iowa"
    t.integer "Kansas"
    t.integer "Kentucky"
    t.integer "Louisiana"
    t.integer "Maine"
    t.integer "Maryland"
    t.integer "Massachusetts"
    t.integer "Michigan"
    t.integer "Minnesota"
    t.integer "Mississippi"
    t.integer "Missouri"
    t.integer "Montana"
    t.integer "Nebraska"
    t.integer "Nevada"
    t.integer "New Hampshire"
    t.integer "New Jersey"
    t.integer "New Mexico"
    t.integer "New York"
    t.integer "North Carolina"
    t.integer "North Dakota"
    t.integer "Ohio"
    t.integer "Oklahoma"
    t.integer "Oregon"
    t.integer "Pennsylvania"
    t.integer "Rhode Island"
    t.integer "South Carolina"
    t.integer "South Dakota"
    t.integer "Tennessee"
    t.integer "Texas"
    t.integer "Utah"
    t.integer "Vermont"
    t.integer "Virginia"
    t.integer "Washington"
    t.integer "West Virginia"
    t.integer "Wisconsin"
    t.integer "Wyoming"
    t.integer "HHS Region 1 (CT, ME, MA, NH, RI, VT)"
    t.integer "HHS Region 2 (NJ, NY)"
    t.integer "HHS Region 3 (DE, DC, MD, PA, VA, WV)"
    t.integer "HHS Region 4 (AL, FL, GA, KY, MS, NC, SC, TN)"
    t.integer "HHS Region 5 (IL, IN, MI, MN, OH, WI)"
    t.integer "HHS Region 6 (AR, LA, NM, OK, TX)"
    t.integer "HHS Region 7 (IA, KS, MO, NE)"
    t.integer "HHS Region 8 (CO, MT, ND, SD, UT, WY)"
    t.integer "HHS Region 9 (AZ, CA, HI, NV)"
    t.integer "HHS Region 10 (AK, ID, OR, WA)"
    t.integer "Anchorage, AK"
    t.integer "Birmingham, AL"
    t.integer "Little Rock, AR"
    t.integer "Mesa, AZ"
    t.integer "Phoenix, AZ"
    t.integer "Scottsdale, AZ"
    t.integer "Tempe, AZ"
    t.integer "Tucson, AZ"
    t.integer "Alameda, CA"
    t.integer "Berkeley, CA"
    t.integer "Beverly Hills, CA"
    t.integer "Fresno, CA"
    t.integer "Irvine, CA"
    t.integer "Los Angeles, CA"
    t.integer "Oakland, CA"
    t.integer "Sacramento, CA"
    t.integer "San Diego, CA"
    t.integer "San Francisco, CA"
    t.integer "San Jose, CA"
    t.integer "Santa Clara, CA"
    t.integer "Sunnyvale, CA"
    t.integer "West Hollywood, CA"
    t.integer "Colorado Springs, CO"
    t.integer "Denver, CO"
    t.integer "Washington, DC"
    t.integer "Gainesville, FL"
    t.integer "Hialeah, FL"
    t.integer "Jacksonville, FL"
    t.integer "Miami, FL"
    t.integer "Orlando, FL"
    t.integer "Tampa, FL"
    t.integer "Atlanta, GA"
    t.integer "Norcross, GA"
    t.integer "Roswell, GA"
    t.integer "Smyrna, GA"
    t.integer "Honolulu, HI"
    t.integer "Des Moines, IA"
    t.integer "Boise, ID"
    t.integer "Chicago, IL"
    t.integer "Harwood Heights, IL"
    t.integer "Indianapolis, IN"
    t.integer "Wichita, KS"
    t.integer "Lexington, KY"
    t.integer "Baton Rouge, LA"
    t.integer "New Orleans, LA"
    t.integer "Boston, MA"
    t.integer "Somerville, MA"
    t.integer "Baltimore, MD"
    t.integer "Takoma Park, MD"
    t.integer "Grand Rapids, MI"
    t.integer "St Paul, MN"
    t.integer "Kansas City, MO"
    t.integer "Springfield, MO"
    t.integer "St Louis, MO"
    t.integer "Jackson, MS"
    t.integer "Cary, NC"
    t.integer "Charlotte, NC"
    t.integer "Durham, NC"
    t.integer "Greensboro, NC"
    t.integer "Raleigh, NC"
    t.integer "Lincoln, NE"
    t.integer "Omaha, NE"
    t.integer "Newark, NJ"
    t.integer "Albuquerque, NM"
    t.integer "Las Vegas, NV"
    t.integer "Reno, NV"
    t.integer "Albany, NY"
    t.integer "Buffalo, NY"
    t.integer "New York, NY"
    t.integer "Rochester, NY"
    t.integer "Cincinnati, OH"
    t.integer "Cleveland, OH"
    t.integer "Columbus, OH"
    t.integer "Dayton, OH"
    t.integer "Oklahoma City, OK"
    t.integer "Tulsa, OK"
    t.integer "Beaverton, OR"
    t.integer "Eugene, OR"
    t.integer "Portland, OR"
    t.integer "Philadelphia, PA"
    t.integer "Pittsburgh, PA"
    t.integer "State College, PA"
    t.integer "Providence, RI"
    t.integer "Columbia, SC"
    t.integer "Greenville, SC"
    t.integer "Knoxville, TN"
    t.integer "Memphis, TN"
    t.integer "Nashville, TN"
    t.integer "Addison, TX"
    t.integer "Austin, TX"
    t.integer "Dallas, TX"
    t.integer "Ft Worth, TX"
    t.integer "Houston, TX"
    t.integer "Irving, TX"
    t.integer "Lubbock, TX"
    t.integer "Plano, TX"
    t.integer "San Antonio, TX"
    t.integer "Midvale, UT"
    t.integer "Salt Lake City, UT"
    t.integer "Arlington, VA"
    t.integer "Ashburn, VA"
    t.integer "Herndon, VA"
    t.integer "Norfolk, VA"
    t.integer "Reston, VA"
    t.integer "Richmond, VA"
    t.integer "Bellevue, WA"
    t.integer "Seattle, WA"
    t.integer "Spokane, WA"
    t.integer "Madison, WI"
    t.integer "Milwaukee, WI"
  end

end
